before_script: 
    - echo "Before Script"
    - hostname
    - echo $index
    - echo $path
    - echo $new

stages:
    - test
    - build
    - deploy

test:
  stage: test
  script: 
    - echo "Running tests"
    - pwd

build:
  stage: build
  script: 
    - echo "Deploy to Deployment server"
    - pwd

deploy_staging:
  stage: deploy
  script:
    - sudo -u splunk /opt/splunk/gitpull.sh
    - cd /tmp/
    - whoami
    - git clone git@gitlab.prod.fedex.com:APP3530768/test-deployment-server.git
    - cd test-deployment-server/deployment-apps/
    - sudo -u splunk cp -r fedex_app_jcls_344_* /opt/splunk/current/etc/deployment-apps/
    - if [ $new = "yes" ] ; then
    - echo "Deploying new app"
    - pwd
    - /opt/splunk/OnpremNewDeployment.sh $index
    - echo "New app Deployed "
    - fi
    - echo "Re-deploying Rest of the apps"
    - exit 0


  only:
  - master

